#pragma once



// Debugging
#ifdef NDEBUG
#define JD_CONSOLE(msg)
#define JD_CONSOLE_FUNCTION(msg)
#else
#include <iostream>

#define JD_DEBUG
#define JD_CONSOLE_STREAM std::cout

#define JD_CONSOLE(msg) JD_CONSOLE_STREAM << msg;
#define JD_CONSOLE_FUNCTION(msg) JD_CONSOLE_STREAM << __PRETTY_FUNCTION__ << " " << msg;
#endif



#ifdef JD_PROFILING
#include "easy/profiler.h"
#include <easy/arbitrary_value.h> // EASY_VALUE, EASY_ARRAY are defined here

#define JD_PROFILING_BLOCK_C(text, color) EASY_BLOCK(text, color)
#define JD_PROFILING_NONSCOPED_BLOCK_C(text, color) EASY_NONSCOPED_BLOCK(text, color)
#define JD_PROFILING_END_BLOCK EASY_END_BLOCK
#define JD_PROFILING_FUNCTION_C(color) EASY_FUNCTION(color)
#define JD_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK_C(text,profiler::colors::  colorStage)
#define JD_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK_C(text,profiler::colors::  colorStage)
#define JD_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION_C(profiler::colors:: colorStage)
#define JD_PROFILING_THREAD(name) EASY_THREAD(name)

#define JD_PROFILING_VALUE(name, value) EASY_VALUE(name, value)
#define JD_PROFILING_TEXT(name, value) EASY_TEXT(name, value)

#else
#define JD_PROFILING_BLOCK_C(text, color)
#define JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_PROFILING_END_BLOCK
#define JD_PROFILING_FUNCTION_C(color)
#define JD_PROFILING_BLOCK(text, colorStage)
#define JD_PROFILING_NONSCOPED_BLOCK(text, colorStage)
#define JD_PROFILING_FUNCTION(colorStage)
#define JD_PROFILING_THREAD(name)

#define JD_PROFILING_VALUE(name, value)
#define JD_PROFILING_TEXT(name, value)
#endif

// Special expantion tecniques are required to combine the color name
#define CONCAT_SYMBOLS_IMPL(x, y) x##y
#define CONCAT_SYMBOLS(x, y) CONCAT_SYMBOLS_IMPL(x, y)



// Different color stages
#define JD_COLOR_STAGE_1 50
#define JD_COLOR_STAGE_2 100
#define JD_COLOR_STAGE_3 200
#define JD_COLOR_STAGE_4 300
#define JD_COLOR_STAGE_5 400
#define JD_COLOR_STAGE_6 500
#define JD_COLOR_STAGE_7 600
#define JD_COLOR_STAGE_8 700
#define JD_COLOR_STAGE_9 800
#define JD_COLOR_STAGE_10 900
#define JD_COLOR_STAGE_11 A100 
#define JD_COLOR_STAGE_12 A200 
#define JD_COLOR_STAGE_13 A400 
#define JD_COLOR_STAGE_14 A700 


// General
#define JD_GENERAL_PROFILING_COLORBASE Cyan
#define JD_GENERAL_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JD_GENERAL_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_GENERAL_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JD_GENERAL_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JD_GENERAL_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JD_GENERAL_PROFILING_COLORBASE, colorStage))
#define JD_GENERAL_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JD_GENERAL_PROFILING_COLORBASE, colorStage))
#define JD_GENERAL_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JD_GENERAL_PROFILING_COLORBASE, colorStage))
#define JD_GENERAL_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JD_GENERAL_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)

// JDObject
#define JD_OBJECT_PROFILING_COLORBASE Blue
#define JD_OBJECT_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JD_OBJECT_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_OBJECT_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JD_OBJECT_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JD_OBJECT_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JD_OBJECT_PROFILING_COLORBASE, colorStage))
#define JD_OBJECT_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JD_OBJECT_PROFILING_COLORBASE, colorStage))
#define JD_OBJECT_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JD_OBJECT_PROFILING_COLORBASE, colorStage))
#define JD_OBJECT_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JD_OBJECT_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)


// File read / write stuff
#define JDFILE_IO_PROFILING_COLORBASE Green
#define JDFILE_IO_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JDFILE_IO_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JDFILE_IO_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JDFILE_IO_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JDFILE_IO_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JDFILE_IO_PROFILING_COLORBASE, colorStage))
#define JDFILE_IO_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JDFILE_IO_PROFILING_COLORBASE, colorStage))
#define JDFILE_IO_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JDFILE_IO_PROFILING_COLORBASE, colorStage))
#define JDFILE_IO_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JDFILE_IO_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)

// FileLock
#define JDFILE_FILE_LOCK_PROFILING_COLORBASE Red
#define JDFILE_FILE_LOCK_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JDFILE_FILE_LOCK_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JDFILE_FILE_LOCK_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JDFILE_FILE_LOCK_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JDFILE_FILE_LOCK_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JDFILE_FILE_LOCK_PROFILING_COLORBASE, colorStage))
#define JDFILE_FILE_LOCK_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JDFILE_FILE_LOCK_PROFILING_COLORBASE, colorStage))
#define JDFILE_FILE_LOCK_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JDFILE_FILE_LOCK_PROFILING_COLORBASE, colorStage))
#define JDFILE_FILE_LOCK_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JDFILE_FILE_LOCK_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)

// JDObjectLocker
#define JD_OBJECT_LOCK_PROFILING_COLORBASE Orange
#define JD_OBJECT_LOCK_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JD_OBJECT_LOCK_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_OBJECT_LOCK_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JD_OBJECT_LOCK_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JD_OBJECT_LOCK_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JD_OBJECT_LOCK_PROFILING_COLORBASE, colorStage))
#define JD_OBJECT_LOCK_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JD_OBJECT_LOCK_PROFILING_COLORBASE, colorStage))
#define JD_OBJECT_LOCK_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JD_OBJECT_LOCK_PROFILING_COLORBASE, colorStage))
#define JD_OBJECT_LOCK_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JD_OBJECT_LOCK_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)


// JDUniqueMutex
#define JD_MUTEX_PROFILING_COLORBASE DeepPurple
#define JD_MUTEX_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JD_MUTEX_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_MUTEX_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JD_MUTEX_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JD_MUTEX_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JD_MUTEX_PROFILING_COLORBASE, colorStage))
#define JD_MUTEX_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JD_MUTEX_PROFILING_COLORBASE, colorStage))
#define JD_MUTEX_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JD_MUTEX_PROFILING_COLORBASE, colorStage))
#define JD_MUTEX_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JD_MUTEX_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)

// Signal
#define JD_SIGNAL_PROFILING_COLORBASE Pink
#define JD_SIGNAL_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JD_SIGNAL_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_SIGNAL_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JD_SIGNAL_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JD_SIGNAL_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JD_SIGNAL_PROFILING_COLORBASE, colorStage))
#define JD_SIGNAL_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JD_SIGNAL_PROFILING_COLORBASE, colorStage))
#define JD_SIGNAL_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JD_SIGNAL_PROFILING_COLORBASE, colorStage))
#define JD_SIGNAL_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JD_SIGNAL_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)

// JDManagerAysncWorker
#define JD_ASYNC_WORKER_PROFILING_COLORBASE Purple
#define JD_ASYNC_WORKER_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JD_ASYNC_WORKER_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_ASYNC_WORKER_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JD_ASYNC_WORKER_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JD_ASYNC_WORKER_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JD_ASYNC_WORKER_PROFILING_COLORBASE, colorStage))
#define JD_ASYNC_WORKER_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JD_ASYNC_WORKER_PROFILING_COLORBASE, colorStage))
#define JD_ASYNC_WORKER_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JD_ASYNC_WORKER_PROFILING_COLORBASE, colorStage))
#define JD_ASYNC_WORKER_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JD_ASYNC_WORKER_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)

// Json Serializer/Deserializer
// #define JD_JSON_PROFILING_ENABED
#ifdef JD_JSON_PROFILING_ENABED
#define JD_JSON_PROFILING_COLORBASE Teal
#define JD_JSON_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JD_JSON_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_JSON_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JD_JSON_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JD_JSON_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JD_JSON_PROFILING_COLORBASE, colorStage))
#define JD_JSON_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JD_JSON_PROFILING_COLORBASE, colorStage))
#define JD_JSON_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JD_JSON_PROFILING_COLORBASE, colorStage))
#define JD_JSON_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JD_JSON_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)
#else
#define JD_JSON_PROFILING_BLOCK_C(text, color) 
#define JD_JSON_PROFILING_NONSCOPED_BLOCK_C(text, color) 
#define JD_JSON_PROFILING_END_BLOCK 
#define JD_JSON_PROFILING_FUNCTION_C(color) 
#define JD_JSON_PROFILING_BLOCK(text, colorStage) 
#define JD_JSON_PROFILING_NONSCOPED_BLOCK(text, colorStage) 
#define JD_JSON_PROFILING_FUNCTION(colorStage) 
#define JD_JSON_PROFILING_VALUE(name, value) 
#define JD_JSON_PROFILING_TEXT(name, value)
#endif

// JDObjectIDDomain
#define JD_ID_DOMAIN_PROFILING_COLORBASE Indigo
#define JD_ID_DOMAIN_PROFILING_BLOCK_C(text, color) JD_PROFILING_BLOCK_C(text, color)
#define JD_ID_DOMAIN_PROFILING_NONSCOPED_BLOCK_C(text, color) JD_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define JD_ID_DOMAIN_PROFILING_END_BLOCK JD_PROFILING_END_BLOCK;
#define JD_ID_DOMAIN_PROFILING_FUNCTION_C(color) JD_PROFILING_FUNCTION_C(color)
#define JD_ID_DOMAIN_PROFILING_BLOCK(text, colorStage) JD_PROFILING_BLOCK(text, CONCAT_SYMBOLS(JD_ID_DOMAIN_PROFILING_COLORBASE, colorStage))
#define JD_ID_DOMAIN_PROFILING_NONSCOPED_BLOCK(text, colorStage) JD_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(JD_ID_DOMAIN_PROFILING_COLORBASE, colorStage))
#define JD_ID_DOMAIN_PROFILING_FUNCTION(colorStage) JD_PROFILING_FUNCTION(CONCAT_SYMBOLS(JD_ID_DOMAIN_PROFILING_COLORBASE, colorStage))
#define JD_ID_DOMAIN_PROFILING_VALUE(name, value) JD_PROFILING_VALUE(name, value)
#define JD_ID_DOMAIN_PROFILING_TEXT(name, value) JD_PROFILING_TEXT(name, value)